name: Redis
version: "8.6.0-alpine"
slug: redis
description: Redis add-on
url: "https://github.com/redis/docker-library-redis"
arch:
  - amd64
  - aarch64
init: false
startup: application
ports:
  6379/tcp: 6379
environment:
  TZ: ${TZ:-UTC}
image: "redis"


